name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to build
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: runner
          tags: 9000hal/metabase:${{ github.event.inputs.version }}
          build-args: VERSION=${{ github.event.inputs.version }}
        env:
          DOCKER_BUILDKIT: 1

  build_and_push_m1:
    name: Build and push Docker image for M1
    runs-on: macos-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./m1.dockerfile
          push: true
          target: runner
          tags: 9000hal/metabase:m1-${{ github.event.inputs.version }}
        env:
          DOCKER_BUILDKIT: 1
